### ISSUE TITLE
Colorblindness Corrections

### ISSUE THREAD

**Issue by rmmilewi** [bssw-psip/psip-automation#2]
The color palette for the Basic, Intermediate, and Advanced buttons is a bit awkward for folks with protanopia (red/green colorblindness), based on results I got back from the Toptal Colorblindness Web Page Filter:

![colorblindness_example](https://user-images.githubusercontent.com/16179797/86819367-c5f99a00-c044-11ea-9fde-fb9f4cd0f1de.png)

I'd recommend using the samples from the IBM colorblind-friendly palette [described here](https://davidmathlogic.com/colorblind/). Here are the substitutions:

**Basic**:   #D81B60
**Intermediate**:   #DC267F
**Advanced** : #FFB000

These colors work well for anyone with protanopia, deuteranopia, or tritanopia.

**Comment by jarrah42** [comment]
The are not perfect but at least you can distinguish between the items.
