### ISSUE TITLE
RateYourProject Feedback: Menu

### ISSUE THREAD

**Issue by elaineraybourn** [bssw-psip/psip-automation#3]
The menu looks great. I like the diamond shaped dashed lines, but using the PSIP logo might be a good call so that there is continuity across our tools and stickers.
It looks like Better Skills is missing from the assessment list. We can add this later.
I like the icons. They are understandable.
![Screen Shot 2020-07-16 at 2 38 51 PM](https://user-images.githubusercontent.com/28600888/87728072-4c725200-c790-11ea-98a9-9bfdb32144b7.png)

**Comment by jarrah42** [comment]
Where can I get the logo?

**Comment by jarrah42** [comment]
Updated. I modified the logo slightly as it didn't fit well in a horizontal space. If this is not ok, let me know and I'll switch back to the original.

**Comment by jarrah42** [comment]
Completed.

**Comment by elaineraybourn** [comment]
looks great!
