### ISSUE TITLE
Can't Clone Repo on Windows

### ISSUE THREAD

**Issue by atshupp** [bssw-psip/psip-automation#44]
I’ve attempted cloning the repository for RYP, and I’m getting an error that seems to be linked to Linux -> Windows incompatibility.  

$ git clone https://github.com/bssw-psip/psip-automation.git
Cloning into 'psip-automation'...
remote: Enumerating objects: 1540, done.
remote: Counting objects: 100% (782/782), done.
remote: Compressing objects: 100% (560/560), done.
remote: Total 1540 (delta 337), reused 567 (delta 186), pack-reused 758
Receiving objects: 100% (1540/1540), 2.26 MiB | 1.55 MiB/s, done.
Resolving deltas: 100% (663/663), done.
error: invalid path 'api/data/versions/RateYourProject 1.0 /RateYourProject 1.0 202105181815.txt'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

I've spoken to Reed about this and he believes it has to do with the directory names.  This website might also be of help: 
[https://stackoverflow.com/questions/61614004/cloning-succeded-but-checkout-failed-due-to-invalid-path-what-is-the-path-probl](url)

**Comment by rmmilewi** [comment]
@jarrah42 FYI, I replicated this bug on my Windows machine. I think there's an issue with having two directories, one of which  is named "RateYourProject 1.0 " (with a space) and another which is named "RateYourProject 1.0" without a space. Something weird is going on there.

**Comment by jarrah42** [comment]
I have renamed all the files and directories to remove spaces. Please try again.

**Comment by atshupp** [comment]
I can confirm this works now.
