### ISSUE TITLE
RateYourProject Feedback: When Finished

### ISSUE THREAD

**Issue by elaineraybourn** [bssw-psip/psip-automation#6]
This is the final view for the end user after the self-assessment has been completed, so a text narrative about the score, and instructions on how to save would be good. The text around diagram is hard to see. Recommend reviewing the colors. Also, is there a way to indicate the total score available for each section and entire self-assessment? We want to know what we are measuring ourselves against.
![Screen Shot 2020-07-16 at 6 24 07 PM](https://user-images.githubusercontent.com/28600888/87728907-1635d200-c792-11ea-8306-e937438aad86.png)

**Comment by jarrah42** [comment]
> This is the final view for the end user after the self-assessment has been completed, so a text narrative about the score, and instructions on how to save would be good. 

Any suggestion on the text would be appreciated!

**Comment by jarrah42** [comment]
> Also, is there a way to indicate the total score available for each section and entire self-assessment? We want to know what we are measuring ourselves against.

The total score is 100 for each section so each section carries the same weight. The score for each item will be 100 divided by the number of items. This means an item from one section may have a greater weight than one from another section if they contain different numbers of items, however I don't think comparing items across sections is meaningful anyway. We're really just interested in them doing as many practices as possible, so this seems to make most sense to me.

**Comment by elaineraybourn** [comment]
Here is my suggestion for text:

The diagram below shows how your project is progressing in all practice areas. You can come back to this page any time to see your progress. When you have completed your assessment be sure to print this page out for your records! We do not save your data in any way. Click on the button below to begin the assessment.

**Comment by jarrah42** [comment]
I think this is now complete.
