### ISSUE TITLE
RateYourProject Homepage text

### ISSUE THREAD

**Issue by elaineraybourn** [bssw-psip/psip-automation#7]
I would put this text on the homepage. Note that I have included all text currently on the homepage in this comment so you can see the formatting:

Software engineering is a systematic approach to the design, development, and maintenance of a software system. Teams seldom have the time to stop development and focus solely on improving productivity or sustainability. However, teams can incorporate improvements on the way to developing new science capabilities.

The tools on this site will help you:

    Assess your current practices
    Create progress tracking cards
    Integrate tracking cards with your workflow 

The self-assessment introduces software engineering practices that increase in maturity. Check the practices that your project already uses to rate your project. Click on the assessment to the left tab to get started. You can also click the arrow icon on the assessment tab to view the practice categories. 

Good luck!

Read the documentation

[in the documentation list I would include a link to https://bssw.io/blog_posts/productivity-and-sustainability-improvement-planning-psip]

**Comment by jarrah42** [comment]
Done.
