### ISSUE TITLE
RateYourProject: Return to homepage

### ISSUE THREAD

**Issue by elaineraybourn** [bssw-psip/psip-automation#8]
Is there a way to get back to the homepage at anytime? I tried finding a clickable homepage image (logo) or tab but could not. This can be helpful if someone wants to go back to the page to read the documentation midway, for example.

**Comment by jarrah42** [comment]
Yes, click Home on the nav bar.

**Comment by elaineraybourn** [comment]
got it!

**Comment by elaineraybourn** [comment]
clicking on home bring you back to documentation
